"""modified roles add permissions

Revision ID: c5d059aca287
Revises: 04c3294886d9
Create Date: 2016-04-12 14:11:09.318013

"""

# revision identifiers, used by Alembic.
revision = 'c5d059aca287'
down_revision = '04c3294886d9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('default', sa.Boolean(), nullable=True))
    op.add_column('roles', sa.Column('permissions', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'permissions')
    op.drop_column('roles', 'default')
    ### end Alembic commands ###
